config/routes.rb
STATIC_PAGES = ['5k', 'contact', 'funding-partners', 'community-partners', 'non-profit-and-corporate-partners',
  'training-partners', 'guide', 'aboutus', 'documentary', 'insurance',
  'get-involved', 'volunteer', 'foster', 'fosterfaq', 'donate', 'sponsor', 'newsletters',
  'special-funds', 'other-ways-to-give', 'terms', 'resources', 'tips-for-finding-lost-pets', 'status_definitions',
  'education-and-outreach','adoption-fee-payments','microchip-registration'].freeze

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/adopters/check_email", to: "adopters#check_email"

  get "/adopters/complete", to: "adopters#complete"

  resources :adopters do
    resources :comments, except: %i[destroy edit update]
    resources :adoptions
    resources :cat_adoptions
  end

  resources :donations do
    collection do
      get 'history', to: 'donations#history'
    end
  end

  resources :comments, except: %i[new]

  resources :cats, controller: 'cats/gallery', only: %i[index show] do
    resources :treatment_records
  end

  resources :dogs, controller: 'dogs/gallery', only: %i[index show] do
    resources :treatment_records
  end

  resources :photos do
    collection { post :sort }
  end

  resources :dogs_manager, controller: 'dogs/manager' do
    resources :comments
    resources :adoptions
    resources :treatment_records
  end

  resources :cats_manager, controller: 'cats/manager' do
    resources :comments
    resources :cat_adoptions
    resources :treatment_records
  end

  resources :volunteer_apps do
    resources :comments, except: %i[destroy edit update]
  end

  resources :bulletins, controller: :posts, type: 'Bulletin'
  resources :opportunities, controller: :posts, type: 'Opportunity'
  resources :infos, controller: :posts, type: 'Info'

  resources :sessions, only: %i[new create destroy]

  get '/events/:scope', to: 'events#index', scope: /(past|upcoming)/, as: "scoped_events"

  get '/campaigns/:scope', to: 'campaigns#index', scope: /(inactive|active)/, as: "scoped_campaigns"

  resources :adoption_app,
            :campaigns,
            :dashboards,
            :events,
            :folders,
            :passwords,
            :password_resets,
            :shelters,
            :treatments,
            :invoices

  resources :invoices do
    member do
      post :record_contract
    end
  end

  resources :adoptions do
    resources :invoices
  end

  resources :cat_adoptions do
    resources :invoices
  end

  resources :attachments, only: %i[show destroy]
  resources :folder_attachments, only: %i[index update]

  resources :users do
    resource :password, controller: :passwords, only: %i[create edit update]
  end

  resources :banned_adopters do
    collection { post :import }
  end

  root to: 'pages#home'

  STATIC_PAGES.each do |page|
    get("/#{page}", to: "pages##{page.underscore}")
  end

  get 'sample_image/:type',    to: 'sample_images#show', constraints: { type: /map/ }, as: 'sample_image'

  get '/signin',               to: 'sessions#new'
  get '/signout',              to: 'sessions#destroy'

  get '/sign_in',              to: 'sessions#new', as: 'sign_in'
  get '/sign_out',             to: 'clearance/sessions#destroy', as: 'sign_out'

  get '/adopt',                to: 'adopters#new'

  get '/international',                                 to: 'pages#international'
  get '/international/kaw',                             to: 'pages#international-kaw'
  get '/international/tcspca',                          to: 'pages#international-tcspca'
  get '/international/volunteer-takes-oph-to-india',    to: 'pages#international-article'
  get '/international/7000-miles-home',                 to: 'pages#7000-miles-home'
  get '/international/hope-for-hope',                  to: 'pages#hope-for-hope'
end

app/models/treatment.rb
#    Copyright 2020 Operation Paws for Homes
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# == Schema Information
#
# Table name: treatments
#
#  id             :bigint           not null, primary key
#  name           :string           not null
#  available_for  :string           not null
#  has_result     :boolean          default(FALSE), not null
#  recommendation :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Treatment < ApplicationRecord
  has_many :treatment_records

  validates :name, presence: true,
                   length: {maximum: 100 }

  AVAILABLE_FOR = ['Dog', 'Cat'].freeze
  validates_inclusion_of :available_for, in: AVAILABLE_FOR, allow_blank: false
end

app/controllers/treatments_controller.rb
#    Copyright 2020 Operation Paws for Homes
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

class TreatmentsController < ApplicationController
  before_action :admin_user
  before_action :select_bootstrap41
  before_action :show_user_navbar

  def index
    @treatments = Treatment.order(:id)
    respond_to do |format|
      format.html
    end
  end

  def show
    @treatment = Treatment.find(params[:id])
    @title = @treatment.name
  end

  def new
    @treatment = Treatment.new
  end

  def create
    @treatment = Treatment.new(treatment_params)
    if @treatment.save
      flash[:success] = "New Treatment Added"
      redirect_to treatments_path
    else
      render 'new'
    end
  end

  def edit
    @treatment = Treatment.find(params[:id])
  end

  def update
    @treatment = Treatment.find(params[:id])
    if @treatment.update(treatment_params)
      flash[:success] = "Record updated."
      redirect_to treatments_path
    else
      render 'edit'
    end
  end

  private

  def treatment_params
    params.require(:treatment).permit(:name,
                                      :available_for,
                                      :has_result,
                                      :recommendation)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/views/treatments/_form.html.erb
<%= form_for @treatment do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
        <div class="form-group">
            <%= f.label :name, 'Treatment Name' %>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :available_for, 'Available For'%>
            <%= f.select(:available_for, Treatment::AVAILABLE_FOR, {prompt: '-select-'}, class: "form-control") %>
        </div>
        <div class="form-check">
            <%= f.check_box :has_result, class: "form-check-input" %>
            <%= f.label :has_result, 'Treatment has a result (Positive/Negative)',class: "form-check-label"%>
        </div>
        <div class="form-group">
            <%= f.label :recommendation, 'Recomendations and Notes' %>
            <%= f.text_area :recommendation, class: "form-control", rows: "3" %>
            <small id="recommendationHelp" class="form-text text-muted">(optional) These notes will be displayed to volunteers when they make an medical entry using this treatment. </small>
        </div>
        <div class="actions well">
            <%= f.submit "Submit", :class => "btn btn-primary" %>
        </div>
<% end %>

app/views/treatments/_treatment.html.erb
<li>
	<%= link_to treatment.name, treatment unless !treatment.name %> - for <%= treatment.available_for.pluralize.downcase %>
</li>

app/views/treatments/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Edit Treatment</h1>
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/treatments/index.html.erb
<div class="container">
    <h1>Treatment Configuration</h1>

    <p>Shots, tests and other treatments listed here can be added to the medical records of a dog or cat. </p>
    <div class="row">
        <div class="col">
            <p><%= link_to "Add Treatment", new_treatment_path, :class => "btn btn-primary" %></p>
        <% if @treatments.count > 0 %>
            <ul class="list-unstyled">
                <%= render @treatments %>
            </ul>
        <% else %>
            <h5>No Treatments Entered</h5>
        <% end %>
        </div>
    </div>
</div>

app/views/treatments/new.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Add Treatment</h1>
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/treatments/show.html.erb
<div class="container">

    <div class="row">
        <div class="col-12">
            <h1 class="py-2">Treatment Configuration</h1>
            <h3><%= @treatment.name %></h3>
            <div class="py-3 pl-3">
                <%= link_to 'Edit Treatment', edit_treatment_path(@treatment), class: 'btn btn-primary' %>
            </div>
            <ul class="list-unstyled">
                <li>This treatment is for <%= @treatment.available_for.pluralize.downcase %></li>
                <% if @treatment.has_result %>
                    <li>has (+/-) test result </li>
                <% end %>
            </ul>
            <div class="pl-3">
                <h5>Recommendations</h5>
                <%= simple_format(@treatment.recommendation) %>
            </div>
        </div>
    </div>
</div>