config/routes.rb
STATIC_PAGES = ['5k', 'contact', 'funding-partners', 'community-partners', 'non-profit-and-corporate-partners',
  'training-partners', 'guide', 'aboutus', 'documentary', 'insurance',
  'get-involved', 'volunteer', 'foster', 'fosterfaq', 'donate', 'sponsor', 'newsletters',
  'special-funds', 'other-ways-to-give', 'terms', 'resources', 'tips-for-finding-lost-pets', 'status_definitions',
  'education-and-outreach','adoption-fee-payments','microchip-registration'].freeze

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/adopters/check_email", to: "adopters#check_email"

  get "/adopters/complete", to: "adopters#complete"

  resources :adopters do
    resources :comments, except: %i[destroy edit update]
    resources :adoptions
    resources :cat_adoptions
  end

  resources :donations do
    collection do
      get 'history', to: 'donations#history'
    end
  end

  resources :comments, except: %i[new]

  resources :cats, controller: 'cats/gallery', only: %i[index show] do
    resources :treatment_records
  end

  resources :dogs, controller: 'dogs/gallery', only: %i[index show] do
    resources :treatment_records
  end

  resources :photos do
    collection { post :sort }
  end

  resources :dogs_manager, controller: 'dogs/manager' do
    resources :comments
    resources :adoptions
    resources :treatment_records
  end

  resources :cats_manager, controller: 'cats/manager' do
    resources :comments
    resources :cat_adoptions
    resources :treatment_records
  end

  resources :volunteer_apps do
    resources :comments, except: %i[destroy edit update]
  end

  resources :bulletins, controller: :posts, type: 'Bulletin'
  resources :opportunities, controller: :posts, type: 'Opportunity'
  resources :infos, controller: :posts, type: 'Info'

  resources :sessions, only: %i[new create destroy]

  get '/events/:scope', to: 'events#index', scope: /(past|upcoming)/, as: "scoped_events"

  get '/campaigns/:scope', to: 'campaigns#index', scope: /(inactive|active)/, as: "scoped_campaigns"

  resources :adoption_app,
            :campaigns,
            :dashboards,
            :events,
            :folders,
            :passwords,
            :password_resets,
            :shelters,
            :treatments,
            :invoices

  resources :invoices do
    member do
      post :record_contract
    end
  end

  resources :adoptions do
    resources :invoices
  end

  resources :cat_adoptions do
    resources :invoices
  end

  resources :attachments, only: %i[show destroy]
  resources :folder_attachments, only: %i[index update]

  resources :users do
    resource :password, controller: :passwords, only: %i[create edit update]
  end

  resources :banned_adopters do
    collection { post :import }
  end

  root to: 'pages#home'

  STATIC_PAGES.each do |page|
    get("/#{page}", to: "pages##{page.underscore}")
  end

  get 'sample_image/:type',    to: 'sample_images#show', constraints: { type: /map/ }, as: 'sample_image'

  get '/signin',               to: 'sessions#new'
  get '/signout',              to: 'sessions#destroy'

  get '/sign_in',              to: 'sessions#new', as: 'sign_in'
  get '/sign_out',             to: 'clearance/sessions#destroy', as: 'sign_out'

  get '/adopt',                to: 'adopters#new'

  get '/international',                                 to: 'pages#international'
  get '/international/kaw',                             to: 'pages#international-kaw'
  get '/international/tcspca',                          to: 'pages#international-tcspca'
  get '/international/volunteer-takes-oph-to-india',    to: 'pages#international-article'
  get '/international/7000-miles-home',                 to: 'pages#7000-miles-home'
  get '/international/hope-for-hope',                  to: 'pages#hope-for-hope'
end

app/models/donation.rb
#    Copyright 2017 Operation Paws for Homes
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# == Schema Information
#
# Table name: donations
#
#  id                 :bigint           not null, primary key
#  stripe_customer_id :string
#  name               :string
#  email              :string
#  amount             :integer
#  frequency          :string
#  card_token         :string
#  notify_someone     :boolean
#  notify_name        :string
#  notify_email       :string
#  notify_message     :string
#  is_memory_honor    :boolean
#  memory_honor_type  :string
#  memory_honor_name  :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  comment            :text
#  campaign_id        :integer
#  more_contact_info  :boolean          default(FALSE)
#  phone              :string
#  address1           :string
#  address2           :string
#  city               :string
#  region             :string(2)
#  postal_code        :string
#

class Donation < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :amount, presence: true
  validates :region, allow_blank: true, length: { maximum: 2 }

  belongs_to :campaign, optional: true

  has_one :invoice

  TSHIRT_SIZE = { "Small" => 'T-Shirt Size: Small',
                  "Medium" => 'T-Shirt Size: Medium',
                  "Large" => 'Tshirt Size: Large',
                  "X-Large" => 'Tshirt Size: X-Large'}.freeze

  MONTHLY_AMOUNTS = [25, 50, 75, 100].freeze

  def create_subscription
    customer = Stripe::Customer.create email: email,
                                       card: card_token

    Stripe::Subscription.create customer: customer,
                                items: [{ plan: ENV['STRIPE_MONTHLY_DONATION_PLAN'],
                                          quantity: amount * 100 }]
  end

  def process_payment
    customer = Stripe::Customer.create email: email,
                                       card: card_token

    Stripe::Charge.create customer: customer.id,
                          amount: amount * 100,
                          description: 'Donation',
                          currency: 'usd'
  end

  def subscription?
    frequency == 'Monthly'
  end
end

app/controllers/donations_controller.rb
#    Copyright 2017 Operation Paws for Homes
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
class DonationsController < ApplicationController
  PER_PAGE = 30

  before_action :require_login, except: %i[new create index]
  before_action :unlocked_user, except: %i[new create index]
  before_action :admin_user, only: %i[history show]
  before_action :select_bootstrap41
  before_action :show_user_navbar, only: %i[history show]

  def new
    @donation = Donation.new optional_params
  end

  def index
    redirect_to(new_donation_path)
  end

  def history
    @donations = Donation.order(created_at: :desc).paginate(page: params[:page], per_page: format_for_page)
    @donation_chart_data = Donation.where(created_at: 12.months.ago..Time.now).group_by_month(:created_at).sum(:amount)
    respond_to do |format|
      format.html
      format.xls { render_donations_xls }
    end
  end

  def show
    @donation = Donation.find(params[:id])
    @related_donations = Donation.where(email: @donation.email)
  end

  def create
    @donation = Donation.new donation_params.merge(card_token: stripe_params["stripeToken"])

    raise "Check for errors" unless @donation.valid?

    if @donation.subscription?
      @donation.create_subscription
    else
      @donation.process_payment
    end

    @donation.save
    DonationMailer.donation_receipt(@donation.id).deliver_later
    DonationMailer.donation_accounting_notification(@donation.id).deliver_later
    if @donation.notify_someone
      DonationMailer.donation_notification(@donation.id).deliver_later
    end
  rescue Stripe::CardError => e
    flash[:error] = e.message
    render :new
  end

  private

  def format_for_page
    return PER_PAGE unless request.format.xls?

    Donation.count
  end

  def admin_user
    redirect_to(new_donation_path) unless current_user.admin?
  end

  def stripe_params
    params.permit :stripeToken,
                  :utf8,
                  :authenticity_token
  end

  def optional_params
    params.permit(:campaign_id,
                  :comment,
                  :frequency,
                  :amount)
  end

  def donation_params
    params.require(:donation).permit(:name,
                                     :email,
                                     :comment,
                                     :amount,
                                     :frequency,
                                     :notify_someone,
                                     :notify_name,
                                     :notify_email,
                                     :notify_message,
                                     :is_memory_honor,
                                     :campaign_id,
                                     :memory_honor_type,
                                     :memory_honor_name,
                                     :more_contact_info,
                                     :phone,
                                     :address1,
                                     :address2,
                                     :city,
                                     :postal_code,
                                     :region)
  end

  def render_donations_xls
    send_data @donations.to_xls(
      filename: 'donations.xls',
      columns: [
        :id,
        :created_at,
        :name,
        :email,
        :amount,
        :comment
      ],
      headers: [
        'ID',
        'Timestamp',
        'Name',
        'Email',
        'Amount',
        'Comment'
      ]
    )
  end
end

app/views/donations/_donation.html.erb
<tr>
    <td><%= donation.created_at.strftime('%m/%d/%Y') %></td>
    <td><%= donation.campaign.try(:title) %>
    <td><%= link_to donation.name, donation %></td>
    <td><%= donation.frequency %></td>
    <td><%= number_to_currency(donation.amount) %></td>
    <td><%= simple_format(donation.comment) %>
</tr>

app/views/donations/_related_donation.html.erb
<li><%= link_to related_donation.created_at.strftime('%m/%d/%Y'), related_donation %> - <%= number_to_currency(related_donation.amount) %> - <%= related_donation.frequency %>

app/views/donations/create.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 offset-md-1 mt-3 pt-3 myBackground">

    <h1>Thank You!</h1>

    <% if @donation.frequency == 'Monthly' %>
      <h4>Thank you for your monthy donation of <strong><%= number_to_currency(@donation.amount) %></strong></h4>

      <p>Thank you for choosing to support Operation Paws for Homes each month.
      Monthly donations like yours provide a stable source of funding for medical care, food, transport and so much more.
      To make changes to your monthly donation in the future, please contact us at <a href='mailto:donate@ophrescue.org'>donate@ophrescue.org</a></p>
    <% else %>
      <h4>Your donation of <strong><%= number_to_currency(@donation.amount) %></strong> has been received.</h4>

      <p>Thank you for your thoughtful donation to Operation Paws for Homes! You make it possible for us to save dogs every single day.
      Your donations help us provide vaccinations, food, transportation, heartworm medicines, spaying and neutering, and so much more.
      We also depend on donations like yours for dogs suffering from severe neglect that require extra attention.</p>
    <% end %>

    <h4>Looking for other ways you can help? It takes a village!</h4>

    <p><strong>Your time</strong> - Regardless of where you live or how much free time you have, there are ways you can volunteer. Visit our <a href="/get-involved">Get Involved</a> page to learn more.</p>
    <p><strong>Your Vehicle</strong> - Operation Paws for Homes has partnered with the Melwood Foundation to accept vehicle donations. For information on how to donate your vehicle to us call 1-877-MEL-WOOD</p>
    <p><strong>Shopping</strong> - Did you know you can shop online and support OPH at the same time? Learn more at <a href="/other-ways-to-give">Other Ways to Give</a></p>
    <p>Above all, thank you for choosing to donate to the OPH Rescue!</p>

      <ul class="list-unstyled">
        <li>Donor Name: <%= @donation.name %></li>
        <li>Donation Date: <%= @donation.created_at.strftime('%m/%d/%y') %> </li>
        <li>Donation Amount: <%= number_to_currency(@donation.amount) %></li>
      </ul>

      <ul class="list-unstyled">
        <li>Operation Paws for Homes</li>
        <li>EIN 45-2785962</li>
        <li>P.O. Box 35606</li>
        <li>N. Chesterfield, VA 23235</li>
        <li>Phone: 703-344-7320</li>
        <li>Fax: 804-302-7975</li>
      </ul>

    </div>
  </div>
</div>

app/views/donations/history.html.erb
<div class="container">
    <div class="row pt-4">
        <div class="col-md-12">
        <h1>Donations</h1>
            <%= area_chart @donation_chart_data, prefix: "$" %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

        <% if @donations.count > 0 %>
            <p>
                Download:
                <%= link_to "Excel", history_donations_path(format: "xls") %>
            </p>

            <%= will_paginate(@donations, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
            <table class="table table-sm table-striped table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Campaign</th>
                        <th scope="col">Name</th>
                        <th scope="col">Frequency</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Comment</th>
                    </tr>
                </thead>
                <tbody>
                    <%= render @donations %>
                </tbody>
            </table>
            <%= will_paginate(@donations, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
        <% else %>
            <h5>No Donations!</h5>
        <% end %>

        </div>
    </div>
</div>

app/views/donations/index.html.erb
<h1>Donations</h1>
<br />

<div class="row">
    <div class="span12">
    <% if @donations.count > 0 %>
        <p>
            Download:
            <%= link_to "Excel", donations_path(format: "xls") %>
        </p>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Donation ID</th>
                    <th>Date</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Amount</th>
                    <th>Zip Code</th>
                    <th>Comment</th>
                </tr>
            </thead>
            <tbody>
                <%= render @donations %>
            </tbody>
        </table>
    <% else %>

        <h5>No Donations!</h5>

    <% end %>

    </div>
</div>

app/views/donations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 offset-md-1 mt-5 pt-3 myBackground">

    <h1>Make a gift. Save a life today.</h1>

    <p>Operation Paws for Homes depends on your generous donations to provide the medical, transportation, fostering, and adoption services needed to place 1,200 homeless dogs in forever homes each year.</p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-7 offset-md-1 pb-3 myBackground">
    <% if @donation.campaign.present? %>
      <div class="alert alert-warning" role="alert">
        You will be donating to <%= @donation.campaign.title %>
      </div>
    <% end %>
    <%= form_for @donation, :html=> { :multipart => true, :class => "form-horizontal" } do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="form-inline">
          <button type="button" class="btn btn-primary btn-lg mx-2 my-2 donationButton" id="donate20" data-toggle="button" value="20">$20</button>
          <button type="button" class="btn btn-primary btn-lg mx-2 my-2 donationButton" id="donate50" data-toggle="button" value="50">$50</button>
          <button type="button" class="btn btn-primary btn-lg mx-2 my-2 donationButton" id="donate75" data-toggle="button" value="75">$75</button>
          <button type="button" class="btn btn-primary btn-lg mx-2 my-2 donationButton" id="donate100" data-toggle="button" value="100">$100</button>
          <button type="button" class="btn btn-primary btn-lg mx-2 my-2 donationButton" id="donate200" data-toggle="button" value="200">$200</button>
          <button type="button" class="btn btn-primary btn-lg mx-2 my-2 donationButton" id="donate500" data-toggle="button" value="500">$500</button>
          <button type="button" class="btn btn-primary btn-lg mx-2 my-2 donationButton" id="donate1000" data-toggle="button" value="1000">$1,000</button>
          <div class="form-group">
            <label for="otherAmount" class="mr-2">Other</label>
            <div class="input-group-prepend">
              <div class="input-group-text">$</div>
            </div>
            <input type="number" id="otherAmount" class="form-control" placeholder="0.00">
          </div>
        </div>
        <div class="form-group form-check form-check-inline">
          <%= f.radio_button :frequency, 'Monthly', class: 'form-check-input', id: 'donation_frequency_monthly' %>
          <%= f.label :frequency_monthly, 'Donate Monthly', class: 'form-check-label'%>
        </div>
        <div class="form-group form-check form-check-inline">
          <%= f.radio_button :frequency, 'Once', class: 'form-check-input', id: 'donation_frequency_once' %>
          <%= f.label :frequency_once, 'Donate Once', class: 'form-check-label'%>
        </div>
        <div class="form-group form-check">
          <%= f.check_box :is_memory_honor, class: 'form-check-input', id: 'honorToggle' %>
          <%= f.label :is_memory_honor, 'Donate in memory or honor of someone', class: 'form-check-label', for: 'honorToggle' %>
        </div>
        <div id="honorFields" class="collapse">
          <div class="form-group form-check form-check-inline">
            <%= f.radio_button :memory_honor_type, 'In memory of', class: 'form-check-input' %>
            <%= f.label :memory_honor_type_in_memory_of, 'In Memory of...', class: 'form-check-label'%>
          </div>
          <div class="form-group form-check form-check-inline">
            <%= f.radio_button :memory_honor_type, 'In honor of', class: 'form-check-input' %>
            <%= f.label :memory_honor_type_in_honor_of, 'In Honor of...', class: 'form-check-label'%>
          </div>
          <div class="form-group">
            <%= f.label :memory_honor_name, 'Honoree\'s Name' %>
            <%= f.text_field :memory_honor_name , class: 'form-control' %>
          </div>
        </div>
        <div class="form-group form-check">
          <%= f.check_box :notify_someone, class: 'form-check-input', id: 'notifyToggle' %>
          <%= f.label :notify_someone, 'Notify someone about your donation', class: 'form-check-label', for: 'notifyToggle' %>
        </div>
        <div id="notifyFields" class="collapse">
          <div class="form-group">
            <%= f.label :notify_name, 'Recipient\'s Name' %>
            <%= f.text_field :notify_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :notify_email, 'Recipient\'s Email' %>
            <%= f.email_field :notify_email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :notify_message, 'Your message to recipient' %>
            <%= f.text_area :notify_message, class: 'form-control', rows: '5' %>
          </div>
        </div>
        <h5>Your Contact Information</h5>
        <div class="form-group">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group form-check">
          <%= f.check_box :more_contact_info, class: 'form-check-input', id: 'moreContactToggle' %>
          <%= f.label :more_contact_info, 'Provide additional contact info', class: 'form-check-label', for: 'moreContactToggle' %>
        </div>
        <div id="moreContactFields" class="collapse">
          <div class="form-group">
            <%= f.label :phone, 'Phone Number' %>
            <%= f.text_field :phone, class: 'form-control', maxlength: 40 %>
          </div>
          <div class="form-group">
            <%= f.label :address1, 'Address 1' %>
            <%= f.text_field :address1, class: 'form-control', maxlength: 250 %>
          </div>
          <div class="form-group">
            <%= f.label :address2, 'Address 2' %>
            <%= f.text_field :address2, class: 'form-control', maxlength: 250 %>
          </div>
          <div class="form-row">
            <div class="form-group col-md-8">
              <%= f.label :city, 'City' %>
              <%= f.text_field :city, class: 'form-control', maxlength: 100 %>
            </div>
            <div class="form-group col-md-2">
              <%= f.label :region, 'State' %>
              <%= f.text_field :region, class: 'form-control', maxlength: 2 %>
            </div>
            <div class="form-group col-md-2">
              <%= f.label :postal_code, 'Zip' %>
              <%= f.text_field :postal_code, class: 'form-control', maxlength: 5 %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :comment, 'Comment' %>
          <%= f.text_area :comment, class: 'form-control', rows: '5' %>
          <small id="commentHelp" class="form-text text-muted">(Optional) Include a short message to OPH about your donation.</small>
        </div>
        <% if @donation.campaign.present? %>
          <%= f.hidden_field(:campaign_id) %>
        <% end %>
        <%= f.hidden_field(:amount) %>
        <%= hidden_field_tag(:stripeToken) %>
        <div id="error_explanation">
          <% if flash[:error].present? %>
              <p><%= flash[:error] %></p>
          <% end %>
        </div>
        <button id="donateButton" class="btn btn-primary btn-lg">Donate</button>
    <% end %>
    </div>
  </div>
</div>

<script>

    let honorToggle = document.getElementById('honorToggle');
    honorToggle.addEventListener('click', function (event) {
      document.getElementById('honorFields').classList.toggle('collapse')
    });

    let notifyToggle = document.getElementById('notifyToggle');
    notifyToggle.addEventListener('click', function (event) {
      document.getElementById('notifyFields').classList.toggle('collapse')
    });

    let moreContactToggle = document.getElementById('moreContactToggle');
    moreContactToggle.addEventListener('click', function (event) {
      document.getElementById('moreContactFields').classList.toggle('collapse')
    });

    let donationAmount = document.getElementById('donation_amount');
    let otherAmount = document.getElementById('otherAmount');

    let otherAmountFunction = function () {
      donationAmount.value = this.value
      resetDonationButtons();
      console.log('Donation value set to :' + donationAmount.value);
    }

    otherAmount.addEventListener('change', otherAmountFunction);

    let donationButtons = document.getElementsByClassName('donationButton');

    let resetDonationButtons = function() {
      for (let i = 0; i < donationButtons.length; i++ ){
        donationButtons[i].classList.remove('btn-success');
        donationButtons[i].removeAttribute('aria-pressed');
        donationButtons[i].classList.remove('active');
        donationButtons[i].classList.add('btn-primary');
      }
    }

    let donationButtonFunction = function() {
      resetDonationButtons();
      otherAmount.value = "$0.00";
      this.classList.remove('btn-primary');
      this.classList.add('btn-success');
      donationAmount.value = this.value;
      console.log('Donation value set to :' + donationAmount.value);
    }

    for (let i = 0; i < donationButtons.length; i++ ) {
      donationButtons[i].addEventListener('click', donationButtonFunction);
    }

    // Support for Montly Giving Club Form

    let url = new URL(document.URL)
    let search_params = new URLSearchParams(url.search);
    let url_amount = search_params.get('amount');

    if (url_amount) {
      console.log('URL has preset donation of :' + url_amount)
      var donate_button = document.getElementById('donate' + url_amount);
      donate_button.click();
    }
</script>

<script src="https://checkout.stripe.com/checkout.js"></script>

<script>
  var handler = StripeCheckout.configure({
    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
    locale: 'auto',
    name: 'Operation Paws for Homes',
    //description: 'One-time donation',
    //panelLabel: 'Donate {{amount}}',
    zipCode: true,
    image: '/apple-touch-icon.png',

    token: function(token) {
      $('input#stripeToken').val(token.id);
      $('form').submit();
    }
  });

  $('#donateButton').on('click', function(e) {
    e.preventDefault();

    $('#error_explanation').html('');

    var email = $('input#donation_email').val();

    var amount = $('#donation_amount').val();
    amount = amount.replace(/\$/g, '').replace(/\,/g, '');

    amount = parseFloat(amount);

    if ($('input#donation_name').val().length == 0) {
      $('#error_explanation').html('<p>Please enter your name.</p>')
      throw "invalid donor name";
    }

    if ($('input#donation_email').val().length == 0) {
      $('#error_explanation').html('<p>Please enter your email address.</p>')
      throw "invalid donor email";
    }

    var frequency = '';

    if ($('#donation_frequency_monthly').prop('checked')) {
      frequency = $('#donation_frequency_monthly').val();
    } else if ($('#donation_frequency_once').prop("checked")) {
      frequency = $('#donation_frequency_once').val();
    } else {
      $('#error_explanation').html('<p>Please choose Donate Monthly or Donate Once.</p>')
      throw "invalid donation type";
    }

    if (frequency == 'Monthly') {
      var description = 'Monthly Donation';
      var panelLabel = 'Donate {{amount}} Monthly';
    }
    else if (frequency == 'Once') {
      var description = 'One Time Donation';
      var panelLabel = 'Donate {{amount}}';
    } else {
      $('#error_explanation').html('<p>Please choose Donate Monthly or Donate Once.</p>');
      throw "invalid donation type";
    }

    if (isNaN(amount)) {
      $('#error_explanation').html('<p>Please enter a valid amount in USD ($).</p>');
    }
    else if (amount < 5.00) {
      $('#error_explanation').html('<p>Donation amount must be at least $5.</p>');
    }
    else {
      amount = amount * 100; // Needs to be an integer!
      handler.open({
        amount: Math.round(amount),
        email: email,
        description: description,
        panelLabel: panelLabel
      })
    }
  });

  // Close Checkout on page navigation
  $(window).on('popstate', function() {
    handler.close();
  });
</script>

app/views/donations/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12 pt-4">
        <h2><%= @donation.name %></h2>

        <div>Donated <%= number_to_currency(@donation.amount) %> <%= @donation.frequency %> at <%= @donation.created_at.strftime('%B %d, %Y %l:%M %p') %></div>
        <%= @donation.campaign.try(:title) %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
        <% if @donation.is_memory_honor %>
            <div>Donated <%= @donation.memory_honor_type %> <%= @donation.memory_honor_name %>.</div>
        <% end %>
        <h4 class="pt-4">Donor Comment</h4>
        <div><%= simple_format(@donation.comment) %></div>

        <h4 class="pt-4">Contact Info</h4>
        <div><%= @donation.email %></div>

        <% if @donation.more_contact_info %>
            <div><%= @donation.phone %></div>
            <div><%= @donation.address1 %></div>
            <div><%= @donation.address2 %></div>
            <div><%= @donation.city %>, <%= @donation.region %> <%= @donation.postal_code %></div>
        <% end %>

        <% if @donation.notify_someone %>
            <h4 class="pt-4">Donor Notified</h4>
            <div><%= @donation.notify_name %></div>
            <div><%= @donation.notify_email %></div>
            <div><%= @donation.notify_message %></div>
        <% end %>


    </div>

    <div class="col-md-6">

        <h5>Related Donations</h5>
        <ul>
            <%= render partial: "related_donation", collection: @related_donations %>
        </ul>

    </div>
</div>