config/routes.rb
STATIC_PAGES = ['5k', 'contact', 'funding-partners', 'community-partners', 'non-profit-and-corporate-partners',
  'training-partners', 'guide', 'aboutus', 'documentary', 'insurance',
  'get-involved', 'volunteer', 'foster', 'fosterfaq', 'donate', 'sponsor', 'newsletters',
  'special-funds', 'other-ways-to-give', 'terms', 'resources', 'tips-for-finding-lost-pets', 'status_definitions',
  'education-and-outreach','adoption-fee-payments','microchip-registration'].freeze

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/adopters/check_email", to: "adopters#check_email"

  get "/adopters/complete", to: "adopters#complete"

  resources :adopters do
    resources :comments, except: %i[destroy edit update]
    resources :adoptions
    resources :cat_adoptions
  end

  resources :donations do
    collection do
      get 'history', to: 'donations#history'
    end
  end

  resources :comments, except: %i[new]

  resources :cats, controller: 'cats/gallery', only: %i[index show] do
    resources :treatment_records
  end

  resources :dogs, controller: 'dogs/gallery', only: %i[index show] do
    resources :treatment_records
  end

  resources :photos do
    collection { post :sort }
  end

  resources :dogs_manager, controller: 'dogs/manager' do
    resources :comments
    resources :adoptions
    resources :treatment_records
  end

  resources :cats_manager, controller: 'cats/manager' do
    resources :comments
    resources :cat_adoptions
    resources :treatment_records
  end

  resources :volunteer_apps do
    resources :comments, except: %i[destroy edit update]
  end

  resources :bulletins, controller: :posts, type: 'Bulletin'
  resources :opportunities, controller: :posts, type: 'Opportunity'
  resources :infos, controller: :posts, type: 'Info'

  resources :sessions, only: %i[new create destroy]

  get '/events/:scope', to: 'events#index', scope: /(past|upcoming)/, as: "scoped_events"

  get '/campaigns/:scope', to: 'campaigns#index', scope: /(inactive|active)/, as: "scoped_campaigns"

  resources :adoption_app,
            :campaigns,
            :dashboards,
            :events,
            :folders,
            :passwords,
            :password_resets,
            :shelters,
            :treatments,
            :invoices

  resources :invoices do
    member do
      post :record_contract
    end
  end

  resources :adoptions do
    resources :invoices
  end

  resources :cat_adoptions do
    resources :invoices
  end

  resources :attachments, only: %i[show destroy]
  resources :folder_attachments, only: %i[index update]

  resources :users do
    resource :password, controller: :passwords, only: %i[create edit update]
  end

  resources :banned_adopters do
    collection { post :import }
  end

  root to: 'pages#home'

  STATIC_PAGES.each do |page|
    get("/#{page}", to: "pages##{page.underscore}")
  end

  get 'sample_image/:type',    to: 'sample_images#show', constraints: { type: /map/ }, as: 'sample_image'

  get '/signin',               to: 'sessions#new'
  get '/signout',              to: 'sessions#destroy'

  get '/sign_in',              to: 'sessions#new', as: 'sign_in'
  get '/sign_out',             to: 'clearance/sessions#destroy', as: 'sign_out'

  get '/adopt',                to: 'adopters#new'

  get '/international',                                 to: 'pages#international'
  get '/international/kaw',                             to: 'pages#international-kaw'
  get '/international/tcspca',                          to: 'pages#international-tcspca'
  get '/international/volunteer-takes-oph-to-india',    to: 'pages#international-article'
  get '/international/7000-miles-home',                 to: 'pages#7000-miles-home'
  get '/international/hope-for-hope',                  to: 'pages#hope-for-hope'
end

app/models/volunteer_app.rb
# == Schema Information
#
# Table name: volunteer_apps
#
#  id                     :bigint           not null, primary key
#  name                   :string
#  email                  :string
#  phone                  :string
#  address1               :string
#  address2               :string
#  city                   :string
#  region                 :string(2)
#  postal_code            :string
#  referrer               :string
#  events_interest        :boolean
#  fostering_interest     :boolean
#  training_interest      :boolean
#  fundraising_interest   :boolean
#  transport_bb_interest  :boolean
#  adoption_team_interest :boolean
#  admin_interest         :boolean
#  about                  :text
#  status                 :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  marketing_interest     :boolean
#
class VolunteerApp < ApplicationRecord
  audited on: :update
  has_associated_audits
  include ClientValidated

  VALIDATION_ERROR_MESSAGES = { name: :blank }

  has_many :volunteer_references, dependent: :destroy
  accepts_nested_attributes_for :volunteer_references

  has_one :volunteer_foster_app, dependent: :destroy
  accepts_nested_attributes_for :volunteer_foster_app

  has_many :comments, -> { order('created_at DESC') }, as: :commentable

  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, presence: true, length: { in: 10..25 }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :address1, presence: true, length: { maximum: 255 }
  validates :address2, allow_blank: true, length: { maximum: 255 }
  validates :city, presence: true, length: { maximum: 255 }
  validates :region, presence: true, length: { is: 2 }
  validates :postal_code, presence: true, length: { in: 5..10 }
  validates :referrer, allow_blank: true, length: { maximum: 255 }
  validates :about, presence: true, length: { maximum: 30000 }

  STATUSES = ['new',
              'workup',
              'ready for call',
              'on hold',
              'approved',
              'withdrawn']

  INTERESTS = ['marketing',
               'events',
               'fostering',
               'training',
               'fundraising',
               'transport',
               'adoption',
               'admin']

  scope :filter_by_status, -> (status) { where status: status }

  def comments_and_audits_and_associated_audits
    (persisted_comments + audits + associated_audits).sort_by(&:created_at).reverse!
  end

  def persisted_comments
    comments.select(&:persisted?)
  end

  def audits_and_associated_audits
    (audits + associated_audits).sort_by(&:created_at).reverse!
  end

  def self.filter_by_interest(interest)
    if interest == 'marketing'
      where(marketing_interest: true)
    elsif interest == 'events'
      where(events_interest: true)
    elsif interest == 'fostering'
      where(fostering_interest: true)
    elsif interest == 'training'
      where(training_interest: true)
    elsif interest == 'fundraising'
      where(fundraising_interest: true)
    elsif interest == 'transport'
      where(transport_bb_interest: true)
    elsif interest == 'adoption'
      where(adoption_team_interest: true)
    elsif interest == 'admin'
      where(admin_interest: true)
    else
      all
    end
  end
end

app/controllers/volunteer_apps_controller.rb
class VolunteerAppsController < ApplicationController
  include ApplicationHelper

  before_action :select_bootstrap41
  before_action :require_login, except: %i(new create complete)
  before_action :admin_user, except: %i(new create complete)

  def index
    @volunteer_apps = VolunteerAppSearcher.search(params: params)
  end

  def show
    @volunteer_app = VolunteerApp.find(params[:id])
    @title = "Volunteer App: " + @volunteer_app.name
  end

  def new
    @volunteer_app = VolunteerApp.new
    @volunteer_app.volunteer_foster_app = VolunteerFosterApp.new
    3.times do
      @volunteer_app.volunteer_references.build
    end
  end

  def update
    @volunteer_app = VolunteerApp.find(params[:id])
    if @volunteer_app.update(volunteer_app_params)
      flash[:success] = 'Application Updated'
      redirect_to @volunteer_app
    else
      render 'show'
    end
  end

  def create
    @volunteer_app = VolunteerApp.new(volunteer_app_params)
    if !@volunteer_app.fostering_interest
      @volunteer_app.volunteer_foster_app = nil
      @volunteer_app.volunteer_references.destroy_all
    end
    @volunteer_app.status = 'new'

    if @volunteer_app.save
      flash[:success] = 'Volunteer Application Submitted Successfully'
      render 'complete'
    else
      render 'new'
    end
  end

  def complete
  end

  private

  def admin_user
    redirect_to(new_volunteer_app_path) unless current_user.admin?
  end

  def volunteer_app_params
    params.require(:volunteer_app).permit(:name,
                                          :email,
                                          :status,
                                          :phone,
                                          :address1,
                                          :address2,
                                          :city,
                                          :region,
                                          :postal_code,
                                          :referrer,
                                          :marketing_interest,
                                          :events_interest,
                                          :fostering_interest,
                                          :training_interest,
                                          :fundraising_interest,
                                          :transport_bb_interest,
                                          :adoption_team_interest,
                                          :admin_interest,
                                          :about,
                                          volunteer_foster_app_attributes:[
                                            :can_foster_dogs,
                                            :can_foster_cats,
                                            :home_type,
                                            :rental_restrictions,
                                            :rental_landlord_name,
                                            :rental_landlord_info,
                                            :has_pets,
                                            :vet_info,
                                            :current_pets,
                                            :current_pets_spay_neuter,
                                            :about_family,
                                            :breed_pref,
                                            :ready_to_foster_dt,
                                            :max_time_alone,
                                            :dog_fenced_in_yard,
                                            :dog_exercise,
                                            :kept_during_day,
                                            :kept_at_night,
                                            :kept_when_alone,
                                            :foster_experience
                                          ],
                                          volunteer_references_attributes:
                                          [
                                            :id,
                                            :name,
                                            :phone,
                                            :email,
                                            :relationship
                                          ])
  end
end

app/views/volunteer_apps/_comment_form.erb
<%= form_for [@volunteer_app, @volunteer_app.comments.build], data: {remote: true}, :html => {novalidate: true, :id => "new_comment"} do |f| %>
  <div class='form-group'>
  <%= f.text_area :content, :class => "form-control comment_content", :rows => "6", :required => true %>
  </div>
  <%= f.submit "Post", class:"btn btn-primary comment_submit", id: "comment_submit" %>

<% end %>

app/views/volunteer_apps/_search.html.erb
<%= form_tag volunteer_apps_path, :method => 'get', :class => 'form-inline' do %>
  <p><%= text_field_tag :search, params[:search], placeholder: 'Search by Name or Email', size: 30, class: "form-control" %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
  <%= link_to "Reset", volunteer_apps_path, class: "btn btn-secondary" %></p>
<% end %>

<%= form_tag volunteer_apps_path, :method => 'get', :class => 'form-inline' do %>
  <p><%= select_tag :status, options_for_select(VolunteerApp::STATUSES.as_options, params[:status]), {include_blank: 'All Statuses', class: "form-control"} %>
  <%= select_tag :interest, options_for_select(VolunteerApp::INTERESTS.as_options, params[:interest]), {include_blank: 'All Interests', class: "form-control"} %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
  <%= link_to "Reset", volunteer_apps_path, class: "btn btn-secondary" %></p>
<% end %>

app/views/volunteer_apps/_volunteer_app.html.erb
<div class="row line-1">
  <div class="col-4">
    <%= link_to volunteer_app.name, volunteer_app %>
    <ul>
      <% if volunteer_app.marketing_interest %>
        <li>Marketing/PR</li>
      <% end %>
      <% if volunteer_app.events_interest %>
      <li>Events</li>
      <% end %>
    <% if volunteer_app.fostering_interest %>
      <li>Fostering</li>
      <% if volunteer_app.volunteer_foster_app.can_foster_dogs %>
          <li>Dog Foster</li>
        <% end %>
        <% if volunteer_app.volunteer_foster_app.can_foster_cats %>
          <li>Cat Foster</li>
        <% end %>
    <% end %>
    <% if volunteer_app.training_interest %>
      <li>Training</li>
    <% end %>
    <% if volunteer_app.fundraising_interest %>
      <li>Fundraising</li>
    <% end %>
    <% if volunteer_app.transport_bb_interest %>
      <li>Transport and Boarding Buddies</li>
    <% end %>
    <% if volunteer_app.adoption_team_interest %>
      <li>Adoption Team</li>
    <% end %>
    <% if volunteer_app.admin_interest %>
      <li>Administrative</li>
    <% end %>
    </ul>
  </div>
  <div class="col-5 offset-1">
    Status: <%= volunteer_app.status.capitalize %> <br />
    <%= volunteer_app.city %>, <%= volunteer_app.region %>
  </div>
</div>

app/views/volunteer_apps/_volunteer_foster_app.html.erb
<dl>
  <dt>Foster Type</dt>
  <dd><%= 'Dogs' if @volunteer_app.volunteer_foster_app.can_foster_dogs %></dd>
  <dd><%= 'Cats' if @volunteer_app.volunteer_foster_app.can_foster_cats %></dd>
  <dt>Home Type</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.home_type %></dd>
  <dt>Rental Restrictions</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.rental_restrictions %></dd>
  <dt>Landlord Info</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.rental_landlord_name %></dd>
  <dd><%= @volunteer_app.volunteer_foster_app.rental_landlord_info %></dd>

  <% if @volunteer_app.volunteer_foster_app.has_pets %>
  <dt>Has Other Pets in Home</dt>
  <dt>Vet Info</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.vet_info %></dd>
  <dt>Curent Pets</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.current_pets %></dd>
  <dt>Spay/Neuter of Current Pets</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.current_pets_spay_neuter %></dd>
  <% end %>

  <dt>About Family</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.about_family %></dd>
  <dt>Breed Preference</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.breed_pref %></dd>
  <dt>Ready to Foster Date</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.ready_to_foster_dt %></dd>
  <dt>Max Time Alone</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.max_time_alone %></dd>
  <% if @volunteer_app.volunteer_foster_app.dog_fenced_in_yard %>
    <dt>Has a fenced in yard</dt>
  <% else %>
    <dt>Does not have a fenced in yard</dt>
  <% end %>
  <dt>Dog Exercise</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.dog_exercise %></dd>
  <dt>Kept During Day</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.kept_during_day %></dd>
  <dt>Kept at Night</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.kept_at_night %></dd>
  <dt>Kept when Alone</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.kept_when_alone %></dd>
  <dt>Foster Experience</dt>
  <dd><%= @volunteer_app.volunteer_foster_app.foster_experience %></dd>
</dl>

<h4>References</h4>
<% @volunteer_app.volunteer_references.each do |ref| %>
  <strong><%= ref.name %><br/></strong>
  <%= ref.email %><br/>
  <%= ref.phone %><br/>
  <%= ref.relationship %><br/>
  <br />
<% end%>

app/views/volunteer_apps/complete.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Thank you for your application</h1>
    </div>
  </div>
</div>

app/views/volunteer_apps/index.html.erb
<div class="container" id="volunteer_app_list">
  <div class="row">
    <div class="col-12">
      <h1 class="mt-3"><%= t('.title') %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'search' %>
    </div>
  </div>

  <%= render @volunteer_apps %>

  <%= will_paginate(@volunteer_apps, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

app/views/volunteer_apps/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-6">
      <h3><%= @volunteer_app.name %></h3>
      <dd>Submitted: <%= @volunteer_app.created_at.strftime('%A, %d %b %Y %l:%M %p') %><dd>
      <ul>
        <% if @volunteer_app.marketing_interest %>
      <li>Marketing/PR</li>
      <% end %>
      <% if @volunteer_app.events_interest %>
          <li>Events</li>
      <% end %>
      <% if @volunteer_app.fostering_interest %>
        <li>Fostering</li>
      <% end %>
      <% if @volunteer_app.training_interest %>
        <li>Training</li>
      <% end %>
      <% if @volunteer_app.fundraising_interest %>
        <li>Fundraising</li>
      <% end %>
      <% if @volunteer_app.transport_bb_interest %>
        <li>Transport and Boarding Buddies</li>
      <% end %>
      <% if @volunteer_app.adoption_team_interest %>
        <li>Adoption Team</li>
      <% end %>
      <% if @volunteer_app.admin_interest %>
        <li>Administrative</li>
      <% end %>
      </ul>

      <dl>
        <dt>Email</dt>
        <dd><%= @volunteer_app.email %></dd>
        <dt>Phone</dt>
        <dd><%= @volunteer_app.phone %></dd>
        <dt>Address</dt>
        <dd><%= @volunteer_app.address1 %></dd>
        <dd><%= @volunteer_app.address2 %></dd>
        <dd><%= @volunteer_app.city %>, <%= @volunteer_app.region %> <%= @volunteer_app.postal_code %></dd>
        <dd><%= @volunteer_app.referrer %></dd>
        <dt>About</dt>
        <dd><%= @volunteer_app.about %></dd>
      </dl>

    <%= form_for @volunteer_app do |f| %>
      <div class="form-group">
        <%= f.label :status %>
        <%= f.select :status, VolunteerApp::STATUSES.collect{|s| [s, s]}, {}, class: "form-control" %>
      </div>
      <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>

    </div>

    <div class="col-6 ml-4">
        <%= render "volunteer_foster_app" if @volunteer_app.fostering_interest %>
    </div>

  </div>
  <div class="row">
    <div class="col-8">

      <h4>Add Comment</h4>
      <%= render 'comment_form' %>

      <%= render 'changes/changes', parent: @volunteer_app, device: '' %>

    </div>
  </div>
</div>