config/routes.rb
STATIC_PAGES = ['5k', 'contact', 'funding-partners', 'community-partners', 'non-profit-and-corporate-partners',
  'training-partners', 'guide', 'aboutus', 'documentary', 'insurance',
  'get-involved', 'volunteer', 'foster', 'fosterfaq', 'donate', 'sponsor', 'newsletters',
  'special-funds', 'other-ways-to-give', 'terms', 'resources', 'tips-for-finding-lost-pets', 'status_definitions',
  'education-and-outreach','adoption-fee-payments','microchip-registration'].freeze

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/adopters/check_email", to: "adopters#check_email"

  get "/adopters/complete", to: "adopters#complete"

  resources :adopters do
    resources :comments, except: %i[destroy edit update]
    resources :adoptions
    resources :cat_adoptions
  end

  resources :donations do
    collection do
      get 'history', to: 'donations#history'
    end
  end

  resources :comments, except: %i[new]

  resources :cats, controller: 'cats/gallery', only: %i[index show] do
    resources :treatment_records
  end

  resources :dogs, controller: 'dogs/gallery', only: %i[index show] do
    resources :treatment_records
  end

  resources :photos do
    collection { post :sort }
  end

  resources :dogs_manager, controller: 'dogs/manager' do
    resources :comments
    resources :adoptions
    resources :treatment_records
  end

  resources :cats_manager, controller: 'cats/manager' do
    resources :comments
    resources :cat_adoptions
    resources :treatment_records
  end

  resources :volunteer_apps do
    resources :comments, except: %i[destroy edit update]
  end

  resources :bulletins, controller: :posts, type: 'Bulletin'
  resources :opportunities, controller: :posts, type: 'Opportunity'
  resources :infos, controller: :posts, type: 'Info'

  resources :sessions, only: %i[new create destroy]

  get '/events/:scope', to: 'events#index', scope: /(past|upcoming)/, as: "scoped_events"

  get '/campaigns/:scope', to: 'campaigns#index', scope: /(inactive|active)/, as: "scoped_campaigns"

  resources :adoption_app,
            :campaigns,
            :dashboards,
            :events,
            :folders,
            :passwords,
            :password_resets,
            :shelters,
            :treatments,
            :invoices

  resources :invoices do
    member do
      post :record_contract
    end
  end

  resources :adoptions do
    resources :invoices
  end

  resources :cat_adoptions do
    resources :invoices
  end

  resources :attachments, only: %i[show destroy]
  resources :folder_attachments, only: %i[index update]

  resources :users do
    resource :password, controller: :passwords, only: %i[create edit update]
  end

  resources :banned_adopters do
    collection { post :import }
  end

  root to: 'pages#home'

  STATIC_PAGES.each do |page|
    get("/#{page}", to: "pages##{page.underscore}")
  end

  get 'sample_image/:type',    to: 'sample_images#show', constraints: { type: /map/ }, as: 'sample_image'

  get '/signin',               to: 'sessions#new'
  get '/signout',              to: 'sessions#destroy'

  get '/sign_in',              to: 'sessions#new', as: 'sign_in'
  get '/sign_out',             to: 'clearance/sessions#destroy', as: 'sign_out'

  get '/adopt',                to: 'adopters#new'

  get '/international',                                 to: 'pages#international'
  get '/international/kaw',                             to: 'pages#international-kaw'
  get '/international/tcspca',                          to: 'pages#international-tcspca'
  get '/international/volunteer-takes-oph-to-india',    to: 'pages#international-article'
  get '/international/7000-miles-home',                 to: 'pages#7000-miles-home'
  get '/international/hope-for-hope',                  to: 'pages#hope-for-hope'
end

app/models/banned_adopter.rb
#    Copyright 2017 Operation Paws for Homes
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# == Schema Information
#
# Table name: banned_adopters
#
#  id         :integer          not null, primary key
#  name       :string(100)
#  phone      :string(20)
#  email      :string(100)
#  city       :string(100)
#  state      :string(2)
#  comment    :text
#  created_at :datetime
#  updated_at :datetime
#

class BannedAdopter < ApplicationRecord
  # def self.open_spreadsheet(file)
  #   case File.extname(file.original_filename)
  #   when '.csv' then Roo::Csv.new(file.path, nil, :ignore)
  #   when '.xls' then Roo::Excel.new(file.path, nil, :ignore)
  #   when '.xlsx' then Roo::Excelx.new(file.path, nil, :ignore)
  #   else raise "Unknown file type: #{file.original_filename}"
  #   end
  # end

  # def self.import(file)
  #   CSV.foreach(file.path, headers: true) do |row|
  #     banned_adopter = find_by_id(row["ID"]) || new
  #     banned_adopter.attributes = row.to_hash.slice(*accessible_attributes)
  #     banned_adopter.save!
  #   end
  # end

  # def self.import(file)
  #   spreadsheet = open_spreadsheet(file)
  #   header = spreadsheet.row(1)
  #   (2..spreadsheet.last_row).each do |i|
  #     row = Hash[[header, spreadsheet.row(i)].transpose]
  #     banned_adopter = find_by_id(row["id"]) || new
  #     banned_adopter.attributes = row.to_hash.slice(*accessible_attributes)
  #     banned_adopter.save!
  #   end
  # end

  validates :name, presence: true
end

app/controllers/banned_adopters_controller.rb
#    Copyright 2017 Operation Paws for Homes
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# == Schema Information
#
# Table name: banned_adopters
#
#  id         :integer          not null, primary key
#  name       :string(100)
#  phone      :string(20)
#  email      :string(100)
#  city       :string(100)
#  state      :string(2)
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BannedAdoptersController < ApplicationController
  before_action :select_bootstrap41
  before_action :require_login
  before_action :unlocked_user
  before_action :active_user
  before_action :ban_adopters_user, only: [:new, :create, :destroy, :edit, :update, :import]

  def index
    @banned_adopters = BannedAdopter.order(:name)
    respond_to do |format|
      format.html
      format.xls { render_banned_adopters_xls }
    end
  end

  def show
    @banned_adopter = BannedAdopter.find(params[:id])
    @title = @banned_adopter.name
  end

  def new
    @banned_adopter = BannedAdopter.new
  end

  def create
    @banned_adopter = BannedAdopter.new(banned_adopter_params)
    if @banned_adopter.save
      flash[:success] = 'New Banned Adopter Added'
      redirect_to banned_adopters_path
    else
      render 'new'
    end
  end

  def edit
    @banned_adopter = BannedAdopter.find(params[:id])
  end

  def update
    @banned_adopter = BannedAdopter.find_by(id: params[:id])
    if @banned_adopter.update(banned_adopter_params)
      flash[:success] = 'Record updated.'
      redirect_to banned_adopters_path
    else
      render 'edit'
    end
  end

  private

  def ban_adopters_user
    redirect_to(root_path) unless current_user.ban_adopters?
  end

  def active_user
    redirect_to(root_path) unless current_user.active?
  end

  def banned_adopter_params
    params
      .require(:banned_adopter)
      .permit(:name,
              :phone,
              :email,
              :city,
              :state,
              :comment)
  end

  def render_banned_adopters_xls
    send_data @banned_adopters.to_xls(
      filename: 'banned_adopters.xls',
      columns: [
        :id,
        :name,
        :phone,
        :email,
        :city,
        :state,
        :comment
      ],
      headers: [
        'id',
        'Name',
        'Phone Number',
        'Email Address',
        'City',
        'State',
        'Comment'
      ]
    )
  end
end

app/views/banned_adopters/_banned_adopter.html.erb
<tr>
	<td><%= link_to banned_adopter.name, banned_adopter unless !banned_adopter.name %></td>
	<td><%= banned_adopter.city unless !banned_adopter.city %>, <%= banned_adopter.state unless !banned_adopter.state %></td>
	<td><%= simple_format(banned_adopter.comment) unless !banned_adopter.comment %></td>
</tr>

app/views/banned_adopters/_form.html.erb
<div class="row">
	<div class="col-8">
		<%= form_for @banned_adopter, :html=> { :multipart => true, :class => "form-horizontal" } do |f| %>
			<%= render 'shared/error_messages', :object => f.object %>
			<fieldset>
				<div class="form-group">
					<label class="mt-2" for="banned_adopter_name">Name</label>
					<%= f.text_field :name, :class => "form-control col-12 col-sm-8 col-md-6 col-lg-4" %>
				</div>

				<div class="form-group">
					<label for="banned_adopter_phone">Phone Number</label>
					<%= f.text_field :phone, :class => "form-control col-10 col-sm-6 col-md-4 col-lg-3" %>
				</div>

				<div class="form-group">
					<label for="banned_adopter_email">Email Address</label>
					<%= f.text_field :email, :class => "form-control col-12 col-sm-8 col-md-6 col-lg-4" %>
				</div>

				<div class="form-group">
					<label for="banned_adopter_city">City</label>
					<%= f.text_field :city, :class => "form-control col-12 col-sm-8 col-md-6 col-lg-4" %>
				</div>

				<div class="form-group">
					<label for="banned_adopter_state">State</label>
					<%= f.text_field :state, :class => "form-control col-4 col-sm-2 col-lg-1" %>
				</div>

				<div class="form-group">
					<label for="banned_adopter_comment">Comment</label>
					<%= f.text_area :comment, :class => "form-control col-12 col-sm-8 col-lg-4", :rows => "5" %>						
				</div>

				<%= f.submit "Submit", :class => "btn btn-primary" %>
			</fieldset>

		<% end %>
	</div>
</div>

app/views/banned_adopters/edit.html.erb
<div class="container-fluid">
    <div class="pages ml-2">
        <h1>Edit</h1>

        <%= render 'form' %>
    </div>
</div>

app/views/banned_adopters/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
			<div class="pages ml-2">
				<h1>Banned Adopters</h1>
				<% if can_ban_adopters? %>
					<p><%= link_to "Add Adopter", new_banned_adopter_path, :class => "btn btn-primary" %>
				<% else %>
					<p>
				<% end %>

				<% if @banned_adopters.count > 0 %>
					<%= link_to "Download Excel", banned_adopters_path(format: "xls"), :class => "btn btn-success ml-2" %></p>
					<table class="table table-striped table-bordered table-sm">
						<thead>
							<tr>
								<th>Name</th>
								<th>Location</th>
								<th>Comment</th>
							</tr>
						</thead>
						<tbody>
							<%= render @banned_adopters %>	
						</tbody>
					</table>
				<% else %>
					<h5>No Banned Adopters</h5>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/banned_adopters/new.html.erb
<div class="container-fluid">
    <div class="pages ml-2">
        <h1>New</h1>

        <%= render 'form' %>
    </div>
</div>

app/views/banned_adopters/show.html.erb
<div class="container-fluid">
	<div class="col-12">
		<div class="pages ml-2">
			<h5 class="mt-4"><%= link_to "Return to List", banned_adopters_path %></h5>

			<h1 class="mb-2"><%= @banned_adopter.name %></h1>

			<table class="table table-striped table-bordered table-sm col-12 col-sm-8 col-md-6 col-lg-4">
				<tr>
					<th>Phone</th>
					<td><%= @banned_adopter.phone %></td>
				</tr>
				<tr>
					<th>Email</th>
					<td><%= @banned_adopter.email %></td>
				</tr>
				<tr>
					<th>Location</th>
					<td><%= @banned_adopter.city %>, <%= @banned_adopter.state %></td>
				</tr>
				<tr>
					<th>Comments</th>
					<td><%= simple_format(@banned_adopter.comment) %></td>
				</tr>
			</table>

			<p><%= link_to "Edit", edit_banned_adopter_path(@banned_adopter), :class => "btn btn-primary btn-small" %></p>
		</div>
	</div>
</div>